<a href="https://colab.research.google.com/github/birichie/AIHackaton/blob/main/LSTM%202%20NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [3]:
def split_sequence(sequence, n_steps):
  X,y = list(), list()
  for i in range(len(sequence)):
    end_ix = i + n_steps
    if end_ix > len(sequence)-1:
      break
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

In [4]:
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
n_steps = 3
X,y = split_sequence(raw_seq, n_steps)
print("summarize the data", raw_seq)
for i in range(len(X)):
  print(X[i]), y[i]
n_features = 1
X=X.reshape((X.shape[0],X.shape[1], n_features))
print("samples", X.shape[0])
print("timesteps", X.shape[1])
print("n-features", n_features)
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')


summarize the data [10, 20, 30, 40, 50, 60, 70, 80, 90]
[10 20 30]
[20 30 40]
[30 40 50]
[40 50 60]
[50 60 70]
[60 70 80]
samples 6
timesteps 3
n-features 1


In [ ]:
model.fit(X,y, epochs=200, verbose=0)
range=[70,80,90]
x_input = 